# Generated by Django 5.1.5 on 2025-01-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lose_count',
            new_name='assets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win_count',
        ),
    ]
