# Generated by Django 5.1.5 on 2025-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_lose_count_profile_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assets',
            field=models.FloatField(default=1000000),
        ),
    ]
