# Generated by Django 5.1.5 on 2025-01-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdailydata',
            unique_together={('game', 'stock', 'date')},
        ),
    ]
