# Generated by Django 5.1.5 on 2025-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockdailydata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='profit_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
