# Generated by Django 5.1.5 on 2025-01-22 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_game_profit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_capital',
            field=models.FloatField(default=1000000),
        ),
        migrations.AddField(
            model_name='game',
            name='ai_profit_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AiTradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('is_buy', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trades', to='stocks.game')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocksymbol')),
            ],
        ),
        migrations.CreateModel(
            name='AiStockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_stock_holdings', to='stocks.game')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocksymbol')),
            ],
            options={
                'unique_together': {('game', 'stock')},
            },
        ),
    ]
