# Generated by Django 5.1.5 on 2025-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_game_ai_capital_game_ai_profit_rate_aitradelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitradelog',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
